### PR TITLE
docs: add API docs for references

### PR DESCRIPTION
**Pull request by buddy326**
Tried to use the `Right` component but for some reason it wasnt recognizing it but I included the file anyways for you to take a look at. I'll just re push the changes and delete the file if its not really correct.

### CODE REVIEW

**Comment by igboyes** [comment]
@buddy326, did you just use the `<Permission />` component instead? I don't see `<Right />` used in the MDX.

**Comment by buddy326** [comment]
I tried using the <Right /> component but it wasnt showing up on the localhost website so i just replaced it with the Permission component instead yes. I included it in the PR tho as I was wondering if you might have an idea as to why it wasnt showing up. Did I have to import it somehow into the other file?

**Comment by igboyes** [comment]
I want to get rid of it. Just use permissions wherever **right** was used for Hugo.

New components have to be imported into `gatsby-browser.js` and added to the `components` object defined in that module.

You also have to restart the dev server to make them work.

**Please remove the `<Right />` component for this PR.**

**Comment by buddy326** [comment]
Fair enough! I'll do that then.

**Review by igboyes — APPROVED** [review]

**Pull request merged**
