### PR TITLE
fix: display legacy sections separately

### PR DESCRIPTION
**Pull request by elanjm12**
Screenshot from 2022-09-23 11-51-38

### CODE REVIEW

**Comment by elanjm12** [comment]
Marked as draft to resolve merge conflict and failing tests

**Comment by elanjm12** [comment]
I believe that my code is now working but there is an issue with some of the new mdx files in data/manual thats preventing the build from completing. I can take a look into what is causing the issues in these files

**Comment by elanjm12** [comment]
Manual renders in docs/legacy_API. Sections are shown on separate pages. For some reason the build would not work unless the index.js file in data/manual/guide/otus and data/manual/guide/samples was removed. Removing the query for this data was not enough to make the build complete without errors.

Screenshot from 2022-10-03 08-22-54

**Review by igboyes — APPROVED** [review]
Thanks @elanjm12. This looks great.

**Pull request merged**
